//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcs.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wcs.Resources.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 依据品种作业 的本地化字符串。
        /// </summary>
        public static string Accordingtoproduct {
            get {
                return ResourceManager.GetString("Accordingtoproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依据轨道作业 的本地化字符串。
        /// </summary>
        public static string Accordingtotrack {
            get {
                return ResourceManager.GetString("Accordingtotrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加库存 的本地化字符串。
        /// </summary>
        public static string Addininventory {
            get {
                return ResourceManager.GetString("Addininventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加库存信息 的本地化字符串。
        /// </summary>
        public static string Addinventorysignal {
            get {
                return ResourceManager.GetString("Addinventorysignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户 的本地化字符串。
        /// </summary>
        public static string Adduser {
            get {
                return ResourceManager.GetString("Adduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员菜单 的本地化字符串。
        /// </summary>
        public static string Administratormenu {
            get {
                return ResourceManager.GetString("Administratormenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上午 的本地化字符串。
        /// </summary>
        public static string Am {
            get {
                return ResourceManager.GetString("Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储砖调度系统 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权管理 的本地化字符串。
        /// </summary>
        public static string Authorizationmanagement {
            get {
                return ResourceManager.GetString("Authorizationmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动对位 的本地化字符串。
        /// </summary>
        public static string Autoaligning {
            get {
                return ResourceManager.GetString("Autoaligning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动模式 的本地化字符串。
        /// </summary>
        public static string Automode {
            get {
                return ResourceManager.GetString("Automode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后侧位置 的本地化字符串。
        /// </summary>
        public static string Backposition {
            get {
                return ResourceManager.GetString("Backposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后侧光电 的本地化字符串。
        /// </summary>
        public static string Backsensor {
            get {
                return ResourceManager.GetString("Backsensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础菜单 的本地化字符串。
        /// </summary>
        public static string Basicmenu {
            get {
                return ResourceManager.GetString("Basicmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        public static string BWD {
            get {
                return ResourceManager.GetString("BWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退复位 的本地化字符串。
        /// </summary>
        public static string BWDreset {
            get {
                return ResourceManager.GetString("BWDreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退至外放砖 的本地化字符串。
        /// </summary>
        public static string BWDtoexternaltilerelease {
            get {
                return ResourceManager.GetString("BWDtoexternaltilerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退至摆渡车 的本地化字符串。
        /// </summary>
        public static string BWDtoferrytrolley {
            get {
                return ResourceManager.GetString("BWDtoferrytrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退至内放砖 的本地化字符串。
        /// </summary>
        public static string BWDtointernaltilerelease {
            get {
                return ResourceManager.GetString("BWDtointernaltilerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退至点 的本地化字符串。
        /// </summary>
        public static string BWDtopointedposition {
            get {
                return ResourceManager.GetString("BWDtopointedposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变更品种 的本地化字符串。
        /// </summary>
        public static string Changeproduct {
            get {
                return ResourceManager.GetString("Changeproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear1 {
            get {
                return ResourceManager.GetString("Clear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有 的本地化字符串。
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭其他 的本地化字符串。
        /// </summary>
        public static string CloseOther {
            get {
                return ResourceManager.GetString("CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色号 的本地化字符串。
        /// </summary>
        public static string Colornumber {
            get {
                return ResourceManager.GetString("Colornumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接通讯 的本地化字符串。
        /// </summary>
        public static string Communicationconnected {
            get {
                return ResourceManager.GetString("Communicationconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中断通讯 的本地化字符串。
        /// </summary>
        public static string Communicationdisconnected {
            get {
                return ResourceManager.GetString("Communicationdisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信正常 的本地化字符串。
        /// </summary>
        public static string Communicationnormal {
            get {
                return ResourceManager.GetString("Communicationnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯状态 的本地化字符串。
        /// </summary>
        public static string Communicationstatus {
            get {
                return ResourceManager.GetString("Communicationstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 握手成功 的本地化字符串。
        /// </summary>
        public static string Communicationsuccessful {
            get {
                return ResourceManager.GetString("Communicationsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成指令 的本地化字符串。
        /// </summary>
        public static string Completedinstruction {
            get {
                return ResourceManager.GetString("Completedinstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理 的本地化字符串。
        /// </summary>
        public static string Configurationmanagement {
            get {
                return ResourceManager.GetString("Configurationmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输车 的本地化字符串。
        /// </summary>
        public static string Conveyingtrolley {
            get {
                return ResourceManager.GetString("Conveyingtrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置坐标 的本地化字符串。
        /// </summary>
        public static string Coordinatesset {
            get {
                return ResourceManager.GetString("Coordinatesset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前坐标 的本地化字符串。
        /// </summary>
        public static string Curentcoordinates {
            get {
                return ResourceManager.GetString("Curentcoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新为当前坐标 的本地化字符串。
        /// </summary>
        public static string Currentcoordinatesrenew {
            get {
                return ResourceManager.GetString("Currentcoordinatesrenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前指令 的本地化字符串。
        /// </summary>
        public static string Currentinstruction {
            get {
                return ResourceManager.GetString("Currentinstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前层数 的本地化字符串。
        /// </summary>
        public static string Currentlayer {
            get {
                return ResourceManager.GetString("Currentlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置 的本地化字符串。
        /// </summary>
        public static string Currentposition {
            get {
                return ResourceManager.GetString("Currentposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前站点 的本地化字符串。
        /// </summary>
        public static string Currentpositioncode {
            get {
                return ResourceManager.GetString("Currentpositioncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前品种 的本地化字符串。
        /// </summary>
        public static string Currentproduct {
            get {
                return ResourceManager.GetString("Currentproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前作业轨道 的本地化字符串。
        /// </summary>
        public static string Currenttrack {
            get {
                return ResourceManager.GetString("Currenttrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除库存 的本地化字符串。
        /// </summary>
        public static string Deleteinventory {
            get {
                return ResourceManager.GetString("Deleteinventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户 的本地化字符串。
        /// </summary>
        public static string Deleteuser {
            get {
                return ResourceManager.GetString("Deleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的坐标 的本地化字符串。
        /// </summary>
        public static string Destinationcoordinates {
            get {
                return ResourceManager.GetString("Destinationcoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标位置 的本地化字符串。
        /// </summary>
        public static string Destinationposition {
            get {
                return ResourceManager.GetString("Destinationposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的位置 的本地化字符串。
        /// </summary>
        public static string Destinationposition1 {
            get {
                return ResourceManager.GetString("Destinationposition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的站点 的本地化字符串。
        /// </summary>
        public static string Destinationstation {
            get {
                return ResourceManager.GetString("Destinationstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录 的本地化字符串。
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接断开 的本地化字符串。
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主动断开 的本地化字符串。
        /// </summary>
        public static string Drivedisconnected {
            get {
                return ResourceManager.GetString("Drivedisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空砖轨道 的本地化字符串。
        /// </summary>
        public static string Emptytrack {
            get {
                return ResourceManager.GetString("Emptytrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介入 的本地化字符串。
        /// </summary>
        public static string Entering {
            get {
                return ResourceManager.GetString("Entering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库轨道 的本地化字符串。
        /// </summary>
        public static string Enterwarehousetrack {
            get {
                return ResourceManager.GetString("Enterwarehousetrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称 的本地化字符串。
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        public static string Equipmenttype {
            get {
                return ResourceManager.GetString("Equipmenttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优等品 的本地化字符串。
        /// </summary>
        public static string Excellentproduct {
            get {
                return ResourceManager.GetString("Excellentproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库轨道 的本地化字符串。
        /// </summary>
        public static string Exitingwarehousetrack {
            get {
                return ResourceManager.GetString("Exitingwarehousetrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 故障 的本地化字符串。
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移车中 的本地化字符串。
        /// </summary>
        public static string Ferrytrolleymoving {
            get {
                return ResourceManager.GetString("Ferrytrolleymoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还车回轨 的本地化字符串。
        /// </summary>
        public static string Ferrytrolleytotrack {
            get {
                return ResourceManager.GetString("Ferrytrolleytotrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小车回轨 的本地化字符串。
        /// </summary>
        public static string Ferrytrolleytracktransferring {
            get {
                return ResourceManager.GetString("Ferrytrolleytracktransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找 的本地化字符串。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级品 的本地化字符串。
        /// </summary>
        public static string First_gradeproduct {
            get {
                return ResourceManager.GetString("First-gradeproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前后边长 的本地化字符串。
        /// </summary>
        public static string Front_backedgelength {
            get {
                return ResourceManager.GetString("Front/backedgelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前侧位置 的本地化字符串。
        /// </summary>
        public static string Frontposition {
            get {
                return ResourceManager.GetString("Frontposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前侧光电 的本地化字符串。
        /// </summary>
        public static string Frontsensor {
            get {
                return ResourceManager.GetString("Frontsensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满砖轨道 的本地化字符串。
        /// </summary>
        public static string Fulltrack {
            get {
                return ResourceManager.GetString("Fulltrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能名称 的本地化字符串。
        /// </summary>
        public static string Functiondescription {
            get {
                return ResourceManager.GetString("Functiondescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 的本地化字符串。
        /// </summary>
        public static string FWD {
            get {
                return ResourceManager.GetString("FWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进复位 的本地化字符串。
        /// </summary>
        public static string FWDreset {
            get {
                return ResourceManager.GetString("FWDreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进至摆渡车 的本地化字符串。
        /// </summary>
        public static string FWDtoferrytrolley {
            get {
                return ResourceManager.GetString("FWDtoferrytrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进至点 的本地化字符串。
        /// </summary>
        public static string FWDtopointedposition {
            get {
                return ResourceManager.GetString("FWDtopointedposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定等级 的本地化字符串。
        /// </summary>
        public static string Gradeset {
            get {
                return ResourceManager.GetString("Gradeset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接中 的本地化字符串。
        /// </summary>
        public static string Inconnecting {
            get {
                return ResourceManager.GetString("Inconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向后插入库存 的本地化字符串。
        /// </summary>
        public static string Insertininvertorybackward {
            get {
                return ResourceManager.GetString("Insertininvertorybackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向前插入库存 的本地化字符串。
        /// </summary>
        public static string Insertininvertoryforward {
            get {
                return ResourceManager.GetString("Insertininvertoryforward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令异常 的本地化字符串。
        /// </summary>
        public static string Instructionabnormal {
            get {
                return ResourceManager.GetString("Instructionabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存序号 的本地化字符串。
        /// </summary>
        public static string Inventorynumber {
            get {
                return ResourceManager.GetString("Inventorynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存位置 的本地化字符串。
        /// </summary>
        public static string Inventoryposition {
            get {
                return ResourceManager.GetString("Inventoryposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存品种 的本地化字符串。
        /// </summary>
        public static string Inventoryproducts {
            get {
                return ResourceManager.GetString("Inventoryproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新库存信息 的本地化字符串。
        /// </summary>
        public static string Inventoryrenew {
            get {
                return ResourceManager.GetString("Inventoryrenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转移库存 的本地化字符串。
        /// </summary>
        public static string Inventorytransferring {
            get {
                return ResourceManager.GetString("Inventorytransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转 的本地化字符串。
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右边长 的本地化字符串。
        /// </summary>
        public static string L_Redgelength {
            get {
                return ResourceManager.GetString("L/Redgelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离开 的本地化字符串。
        /// </summary>
        public static string Leaving {
            get {
                return ResourceManager.GetString("Leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上下砖机 的本地化字符串。
        /// </summary>
        public static string Loading_unloadingmachine {
            get {
                return ResourceManager.GetString("Loading/unloadingmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取货坐标 的本地化字符串。
        /// </summary>
        public static string Loadingcoordinates {
            get {
                return ResourceManager.GetString("Loadingcoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上砖摆渡轨道 的本地化字符串。
        /// </summary>
        public static string Loadingferrytrack {
            get {
                return ResourceManager.GetString("Loadingferrytrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上砖摆渡车 的本地化字符串。
        /// </summary>
        public static string Loadingferrytrolley {
            get {
                return ResourceManager.GetString("Loadingferrytrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上砖机 的本地化字符串。
        /// </summary>
        public static string Loadingmachine {
            get {
                return ResourceManager.GetString("Loadingmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅上砖 的本地化字符串。
        /// </summary>
        public static string LoadingONLY {
            get {
                return ResourceManager.GetString("LoadingONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取货站点 的本地化字符串。
        /// </summary>
        public static string Loadingposition {
            get {
                return ResourceManager.GetString("Loadingposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载货状态 的本地化字符串。
        /// </summary>
        public static string Loadingstatus {
            get {
                return ResourceManager.GetString("Loadingstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载车状态 的本地化字符串。
        /// </summary>
        public static string Loadingstatus1 {
            get {
                return ResourceManager.GetString("Loadingstatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载砖状态 的本地化字符串。
        /// </summary>
        public static string Loadingstatus2 {
            get {
                return ResourceManager.GetString("Loadingstatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上砖任务 的本地化字符串。
        /// </summary>
        public static string Loadingtask {
            get {
                return ResourceManager.GetString("Loadingtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上砖轨道 的本地化字符串。
        /// </summary>
        public static string Loadingtrack {
            get {
                return ResourceManager.GetString("Loadingtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载车 的本地化字符串。
        /// </summary>
        public static string Loadingtrolley {
            get {
                return ResourceManager.GetString("Loadingtrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户： 的本地化字符串。
        /// </summary>
        public static string LoginUser {
            get {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动上砖 的本地化字符串。
        /// </summary>
        public static string Manualloading {
            get {
                return ResourceManager.GetString("Manualloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动模式 的本地化字符串。
        /// </summary>
        public static string Manualmode {
            get {
                return ResourceManager.GetString("Manualmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动下砖 的本地化字符串。
        /// </summary>
        public static string Manualunloading {
            get {
                return ResourceManager.GetString("Manualunloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满砖层数 的本地化字符串。
        /// </summary>
        public static string Max_tilelayer {
            get {
                return ResourceManager.GetString("Max.tilelayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户 的本地化字符串。
        /// </summary>
        public static string Modifyuser {
            get {
                return ResourceManager.GetString("Modifyuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变作业依据 的本地化字符串。
        /// </summary>
        public static string Modifyworkingcondition {
            get {
                return ResourceManager.GetString("Modifyworkingcondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窄车 的本地化字符串。
        /// </summary>
        public static string Narrowtrolley {
            get {
                return ResourceManager.GetString("Narrowtrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有指令 的本地化字符串。
        /// </summary>
        public static string Noinstruction {
            get {
                return ResourceManager.GetString("Noinstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非空 的本地化字符串。
        /// </summary>
        public static string Notempty {
            get {
                return ResourceManager.GetString("Notempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非空非满 的本地化字符串。
        /// </summary>
        public static string Notempty1 {
            get {
                return ResourceManager.GetString("Notempty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有砖轨道 的本地化字符串。
        /// </summary>
        public static string Notemptytrack {
            get {
                return ResourceManager.GetString("Notemptytrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线报警 的本地化字符串。
        /// </summary>
        public static string Off_linewarning {
            get {
                return ResourceManager.GetString("Off-linewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作模式 的本地化字符串。
        /// </summary>
        public static string Operatingmode {
            get {
                return ResourceManager.GetString("Operatingmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下降放货 的本地化字符串。
        /// </summary>
        public static string Origindownunloading {
            get {
                return ResourceManager.GetString("Origindownunloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶升取货 的本地化字符串。
        /// </summary>
        public static string Originuploading {
            get {
                return ResourceManager.GetString("Originuploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级目录 的本地化字符串。
        /// </summary>
        public static string Parentdirectory {
            get {
                return ResourceManager.GetString("Parentdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验密码 的本地化字符串。
        /// </summary>
        public static string Passwordcheck {
            get {
                return ResourceManager.GetString("Passwordcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下午 的本地化字符串。
        /// </summary>
        public static string Pm {
            get {
                return ResourceManager.GetString("Pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位指令 的本地化字符串。
        /// </summary>
        public static string Positioninstruction {
            get {
                return ResourceManager.GetString("Positioninstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string Prioritygrade {
            get {
                return ResourceManager.GetString("Prioritygrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产时间 的本地化字符串。
        /// </summary>
        public static string Producingtime {
            get {
                return ResourceManager.GetString("Producingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转产完成 的本地化字符串。
        /// </summary>
        public static string Productchanged {
            get {
                return ResourceManager.GetString("Productchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转产状态 的本地化字符串。
        /// </summary>
        public static string Productchangestatus {
            get {
                return ResourceManager.GetString("Productchangestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转产中 的本地化字符串。
        /// </summary>
        public static string Productchanging {
            get {
                return ResourceManager.GetString("Productchanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品种名称 的本地化字符串。
        /// </summary>
        public static string Productiondescription {
            get {
                return ResourceManager.GetString("Productiondescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定品种 的本地化字符串。
        /// </summary>
        public static string Productset {
            get {
                return ResourceManager.GetString("Productset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脉冲值 的本地化字符串。
        /// </summary>
        public static string Pulsevalue {
            get {
                return ResourceManager.GetString("Pulsevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格品 的本地化字符串。
        /// </summary>
        public static string Qualifiedproduct {
            get {
                return ResourceManager.GetString("Qualifiedproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阅读器断开报警 的本地化字符串。
        /// </summary>
        public static string Readerdisconnectwarning {
            get {
                return ResourceManager.GetString("Readerdisconnectwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存实际坐标 的本地化字符串。
        /// </summary>
        public static string Realinventorycoordinates {
            get {
                return ResourceManager.GetString("Realinventorycoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际点位 的本地化字符串。
        /// </summary>
        public static string Realposition {
            get {
                return ResourceManager.GetString("Realposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求状态 的本地化字符串。
        /// </summary>
        public static string Requirementstatus {
            get {
                return ResourceManager.GetString("Requirementstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位指令 的本地化字符串。
        /// </summary>
        public static string Resetinstruction {
            get {
                return ResourceManager.GetString("Resetinstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退倒库 的本地化字符串。
        /// </summary>
        public static string ReturingwarehouseBWD {
            get {
                return ResourceManager.GetString("ReturingwarehouseBWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进倒库 的本地化字符串。
        /// </summary>
        public static string ReturingwarehouseFWD {
            get {
                return ResourceManager.GetString("ReturingwarehouseFWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒库中 的本地化字符串。
        /// </summary>
        public static string Returningtowarehouse {
            get {
                return ResourceManager.GetString("Returningtowarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒库 的本地化字符串。
        /// </summary>
        public static string Returningtowarehouse1 {
            get {
                return ResourceManager.GetString("Returningtowarehouse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒库任务 的本地化字符串。
        /// </summary>
        public static string Returntowarehouse {
            get {
                return ResourceManager.GetString("Returntowarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动状态 的本地化字符串。
        /// </summary>
        public static string Runningstatus {
            get {
                return ResourceManager.GetString("Runningstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同向上砖 的本地化字符串。
        /// </summary>
        public static string Samedirectionloading {
            get {
                return ResourceManager.GetString("Samedirectionloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同向下砖 的本地化字符串。
        /// </summary>
        public static string Samedirectionunloading {
            get {
                return ResourceManager.GetString("Samedirectionunloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更新至后台 的本地化字符串。
        /// </summary>
        public static string Saverenew {
            get {
                return ResourceManager.GetString("Saverenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调度设备 的本地化字符串。
        /// </summary>
        public static string Schedulingequipment {
            get {
                return ResourceManager.GetString("Schedulingequipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级品 的本地化字符串。
        /// </summary>
        public static string Second_gradeproduct {
            get {
                return ResourceManager.GetString("Second-gradeproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存放垛数 的本地化字符串。
        /// </summary>
        public static string Stackqty {
            get {
                return ResourceManager.GetString("Stackqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态 的本地化字符串。
        /// </summary>
        public static string Start1 {
            get {
                return ResourceManager.GetString("Start1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string Starttime {
            get {
                return ResourceManager.GetString("Starttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop1 {
            get {
                return ResourceManager.GetString("Stop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终止指令 的本地化字符串。
        /// </summary>
        public static string Stopinstruction {
            get {
                return ResourceManager.GetString("Stopinstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string Stoptime {
            get {
                return ResourceManager.GetString("Stoptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改策略 的本地化字符串。
        /// </summary>
        public static string Strategymodify {
            get {
                return ResourceManager.GetString("Strategymodify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消任务 的本地化字符串。
        /// </summary>
        public static string Taskcancelled {
            get {
                return ResourceManager.GetString("Taskcancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成任务 的本地化字符串。
        /// </summary>
        public static string Taskcompleted {
            get {
                return ResourceManager.GetString("Taskcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开关 的本地化字符串。
        /// </summary>
        public static string Taskswitch {
            get {
                return ResourceManager.GetString("Taskswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务类型 的本地化字符串。
        /// </summary>
        public static string Tasktype {
            get {
                return ResourceManager.GetString("Tasktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务类型 的本地化字符串。
        /// </summary>
        public static string Tasktype1 {
            get {
                return ResourceManager.GetString("Tasktype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取砖流程 的本地化字符串。
        /// </summary>
        public static string Tilecatching {
            get {
                return ResourceManager.GetString("Tilecatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无砖 的本地化字符串。
        /// </summary>
        public static string Tilelack {
            get {
                return ResourceManager.GetString("Tilelack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退取砖 的本地化字符串。
        /// </summary>
        public static string TileloadingBWD {
            get {
                return ResourceManager.GetString("TileloadingBWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进取砖 的本地化字符串。
        /// </summary>
        public static string TileloadingFWD {
            get {
                return ResourceManager.GetString("TileloadingFWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取砖指令 的本地化字符串。
        /// </summary>
        public static string Tileloadinginstruction {
            get {
                return ResourceManager.GetString("Tileloadinginstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存放片数 的本地化字符串。
        /// </summary>
        public static string Tileqty {
            get {
                return ResourceManager.GetString("Tileqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道库存 的本地化字符串。
        /// </summary>
        public static string Tileqtyontrack {
            get {
                return ResourceManager.GetString("Tileqtyontrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有砖 的本地化字符串。
        /// </summary>
        public static string Tileready {
            get {
                return ResourceManager.GetString("Tileready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放砖流程 的本地化字符串。
        /// </summary>
        public static string Tilereleasing {
            get {
                return ResourceManager.GetString("Tilereleasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进放砖 的本地化字符串。
        /// </summary>
        public static string TilereleasingFWD {
            get {
                return ResourceManager.GetString("TilereleasingFWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放砖指令 的本地化字符串。
        /// </summary>
        public static string Tilereleasinginstruction {
            get {
                return ResourceManager.GetString("Tilereleasinginstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储砖轨道 的本地化字符串。
        /// </summary>
        public static string Tilestoragetrack {
            get {
                return ResourceManager.GetString("Tilestoragetrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过大 的本地化字符串。
        /// </summary>
        public static string TooLarge {
            get {
                return ResourceManager.GetString("TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查轨道 的本地化字符串。
        /// </summary>
        public static string Trackcheck {
            get {
                return ResourceManager.GetString("Trackcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道名称 的本地化字符串。
        /// </summary>
        public static string Trackdescription {
            get {
                return ResourceManager.GetString("Trackdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空轨信号 的本地化字符串。
        /// </summary>
        public static string Trackemptysignal {
            get {
                return ResourceManager.GetString("Trackemptysignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道尾部 的本地化字符串。
        /// </summary>
        public static string Trackend {
            get {
                return ResourceManager.GetString("Trackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满轨信号 的本地化字符串。
        /// </summary>
        public static string Trackfullsignal {
            get {
                return ResourceManager.GetString("Trackfullsignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道头部 的本地化字符串。
        /// </summary>
        public static string Trackhead {
            get {
                return ResourceManager.GetString("Trackhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道中部 的本地化字符串。
        /// </summary>
        public static string Trackmid {
            get {
                return ResourceManager.GetString("Trackmid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道读点报警 的本地化字符串。
        /// </summary>
        public static string Trackreadingwarning {
            get {
                return ResourceManager.GetString("Trackreadingwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用轨道 的本地化字符串。
        /// </summary>
        public static string Trackstarted {
            get {
                return ResourceManager.GetString("Trackstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道状态 的本地化字符串。
        /// </summary>
        public static string Trackstatus {
            get {
                return ResourceManager.GetString("Trackstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空满信号 的本地化字符串。
        /// </summary>
        public static string Trackstatussignal {
            get {
                return ResourceManager.GetString("Trackstatussignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用轨道 的本地化字符串。
        /// </summary>
        public static string Trackstopped {
            get {
                return ResourceManager.GetString("Trackstopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道类型 的本地化字符串。
        /// </summary>
        public static string Tracktype {
            get {
                return ResourceManager.GetString("Tracktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空车 的本地化字符串。
        /// </summary>
        public static string Trolleyempty {
            get {
                return ResourceManager.GetString("Trolleyempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存放车数 的本地化字符串。
        /// </summary>
        public static string Trolleyqty {
            get {
                return ResourceManager.GetString("Trolleyqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移车任务 的本地化字符串。
        /// </summary>
        public static string Truckmovement {
            get {
                return ResourceManager.GetString("Truckmovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知大小 的本地化字符串。
        /// </summary>
        public static string UnknownSize {
            get {
                return ResourceManager.GetString("UnknownSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸货坐标 的本地化字符串。
        /// </summary>
        public static string Unloadingcoordinates {
            get {
                return ResourceManager.GetString("Unloadingcoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下砖摆渡轨道 的本地化字符串。
        /// </summary>
        public static string Unloadingferrytrack {
            get {
                return ResourceManager.GetString("Unloadingferrytrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下砖摆渡车 的本地化字符串。
        /// </summary>
        public static string Unloadingferrytrolley {
            get {
                return ResourceManager.GetString("Unloadingferrytrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下砖机 的本地化字符串。
        /// </summary>
        public static string Unloadingmachine {
            get {
                return ResourceManager.GetString("Unloadingmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅下砖 的本地化字符串。
        /// </summary>
        public static string UnloadingONLY {
            get {
                return ResourceManager.GetString("UnloadingONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸货站点 的本地化字符串。
        /// </summary>
        public static string Unloadingposition {
            get {
                return ResourceManager.GetString("Unloadingposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下砖任务 的本地化字符串。
        /// </summary>
        public static string Unloadingtask {
            get {
                return ResourceManager.GetString("Unloadingtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下砖轨道 的本地化字符串。
        /// </summary>
        public static string Unloadingtrack {
            get {
                return ResourceManager.GetString("Unloadingtrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库策略 的本地化字符串。
        /// </summary>
        public static string Warehouseinstrategy {
            get {
                return ResourceManager.GetString("Warehouseinstrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库策略 的本地化字符串。
        /// </summary>
        public static string Warehouseoutstrategy {
            get {
                return ResourceManager.GetString("Warehouseoutstrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒库数量 的本地化字符串。
        /// </summary>
        public static string Warehousereturningqty {
            get {
                return ResourceManager.GetString("Warehousereturningqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告类型 的本地化字符串。
        /// </summary>
        public static string Warningtype {
            get {
                return ResourceManager.GetString("Warningtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽车 的本地化字符串。
        /// </summary>
        public static string Widetrolley {
            get {
                return ResourceManager.GetString("Widetrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业依据 的本地化字符串。
        /// </summary>
        public static string Workingcondition {
            get {
                return ResourceManager.GetString("Workingcondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换工作模式 的本地化字符串。
        /// </summary>
        public static string Workingmodeshift {
            get {
                return ResourceManager.GetString("Workingmodeshift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位品种 的本地化字符串。
        /// </summary>
        public static string Workstationproduct {
            get {
                return ResourceManager.GetString("Workstationproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
